# yaml-language-server: schema: https://raw.githubusercontent.com/pnpm/pnpm/main/schemas/workspace.yaml

packages:
  - packages/**
  - config
  - playgrounds/**

catalog:
  '@vitest/browser-playwright': 4.0.4
  '@vitest/coverage-v8': 4.0.4
  eslint: 9.38.0
  oxlint: 1.24.0
  oxlint-tsgolint: 0.3.0
  prettier: 3.6.2
  tsdown: 0.16.4
  typescript: ^5.9.3
  vitest: 4.0.4
