packages:
  - packages/**
  - config

catalog:
  '@vitest/coverage-v8': ^3.2.4
  eslint: 9.35.0
  oxlint: 1.19.0
  oxlint-tsgolint: 0.2.0
  prettier: 3.6.2
  tsdown: 0.15.6
  typescript: ^5.9.3
  vitest: ^3.2.4
