import { Computed } from "@dathomir/reactivity";

import { AIntrinsicElements } from "./IntrinsicElements/A";
import { AbbrIntrinsicElements } from "./IntrinsicElements/Abbr";
import { AddressIntrinsicElements } from "./IntrinsicElements/Address";
import { AreaIntrinsicElements } from "./IntrinsicElements/Area";
import { ArticleIntrinsicElements } from "./IntrinsicElements/Article";
import { AsideIntrinsicElements } from "./IntrinsicElements/Aside";
import { AudioIntrinsicElements } from "./IntrinsicElements/Audio";
import { BIntrinsicElements } from "./IntrinsicElements/B";
import { BaseIntrinsicElements } from "./IntrinsicElements/Base";
import { BdiIntrinsicElements } from "./IntrinsicElements/Bdi";
import { BdoIntrinsicElements } from "./IntrinsicElements/Bdo";
import { BlockquoteIntrinsicElements } from "./IntrinsicElements/Blockquote";
import { BodyIntrinsicElements } from "./IntrinsicElements/Body";
import { BrIntrinsicElements } from "./IntrinsicElements/Br";
import { ButtonIntrinsicElements } from "./IntrinsicElements/Button";
import { CanvasIntrinsicElements } from "./IntrinsicElements/Canvas";
import { CaptionIntrinsicElements } from "./IntrinsicElements/Caption";
import { CiteIntrinsicElements } from "./IntrinsicElements/Cite";
import { CodeIntrinsicElements } from "./IntrinsicElements/Code";
import { ColIntrinsicElements } from "./IntrinsicElements/Col";
import { ColgroupIntrinsicElements } from "./IntrinsicElements/Colgroup";
import { DataIntrinsicElements } from "./IntrinsicElements/Data";
import { DatalistIntrinsicElements } from "./IntrinsicElements/Datalist";
import { DdIntrinsicElements } from "./IntrinsicElements/Dd";
import { DelIntrinsicElements } from "./IntrinsicElements/Del";
import { DetailsIntrinsicElements } from "./IntrinsicElements/Details";
import { DfnIntrinsicElements } from "./IntrinsicElements/Dfn";
import { DialogIntrinsicElements } from "./IntrinsicElements/Dialog";
import { DivIntrinsicElements } from "./IntrinsicElements/Div";
import { DlIntrinsicElements } from "./IntrinsicElements/Dl";
import { DtIntrinsicElements } from "./IntrinsicElements/Dt";
import { EmIntrinsicElements } from "./IntrinsicElements/Em";
import { EmbedIntrinsicElements } from "./IntrinsicElements/Embed";
import { FencedframeIntrinsicElements } from "./IntrinsicElements/Fencedframe";
import { FieldsetIntrinsicElements } from "./IntrinsicElements/Fieldset";
import { FigcaptionIntrinsicElements } from "./IntrinsicElements/Figcaption";
import { FigureIntrinsicElements } from "./IntrinsicElements/Figure";
import { FooterIntrinsicElements } from "./IntrinsicElements/Footer";
import { FormIntrinsicElements } from "./IntrinsicElements/Form";
import { H1IntrinsicElements } from "./IntrinsicElements/H1";
import { H2IntrinsicElements } from "./IntrinsicElements/H2";
import { H3IntrinsicElements } from "./IntrinsicElements/H3";
import { H4IntrinsicElements } from "./IntrinsicElements/H4";
import { H5IntrinsicElements } from "./IntrinsicElements/H5";
import { H6IntrinsicElements } from "./IntrinsicElements/H6";
import { HeadIntrinsicElements } from "./IntrinsicElements/Head";
import { HeaderIntrinsicElements } from "./IntrinsicElements/Header";
import { HgroupIntrinsicElements } from "./IntrinsicElements/Hgroup";
import { HrIntrinsicElements } from "./IntrinsicElements/Hr";
import { HtmlIntrinsicElements } from "./IntrinsicElements/Html";
import { IIntrinsicElements } from "./IntrinsicElements/I";
import { IframeIntrinsicElements } from "./IntrinsicElements/Iframe";
import { ImgIntrinsicElements } from "./IntrinsicElements/Img";
import { InputIntrinsicElements } from "./IntrinsicElements/Input";
import { InsIntrinsicElements } from "./IntrinsicElements/Ins";
import { KbdIntrinsicElements } from "./IntrinsicElements/Kbd";
import { LabelIntrinsicElements } from "./IntrinsicElements/Label";
import { LegendIntrinsicElements } from "./IntrinsicElements/Legend";
import { LiIntrinsicElements } from "./IntrinsicElements/Li";
import { LinkIntrinsicElements } from "./IntrinsicElements/Link";
import { MainIntrinsicElements } from "./IntrinsicElements/Main";
import { MapIntrinsicElements } from "./IntrinsicElements/Map";
import { MarkIntrinsicElements } from "./IntrinsicElements/Mark";
import { MathIntrinsicElements } from "./IntrinsicElements/Math";
import { MenuIntrinsicElements } from "./IntrinsicElements/Menu";
import { MetaIntrinsicElements } from "./IntrinsicElements/Meta";
import { MeterIntrinsicElements } from "./IntrinsicElements/Meter";
import { NavIntrinsicElements } from "./IntrinsicElements/Nav";
import { NoscriptIntrinsicElements } from "./IntrinsicElements/Noscript";
import { ObjectIntrinsicElements } from "./IntrinsicElements/Object";
import { OlIntrinsicElements } from "./IntrinsicElements/Ol";
import { OptgroupIntrinsicElements } from "./IntrinsicElements/Optgroup";
import { OptionIntrinsicElements } from "./IntrinsicElements/Option";
import { OutputIntrinsicElements } from "./IntrinsicElements/Output";
import { PIntrinsicElements } from "./IntrinsicElements/P";
import { PictureIntrinsicElements } from "./IntrinsicElements/Picture";
import { PreIntrinsicElements } from "./IntrinsicElements/Pre";
import { ProgressIntrinsicElements } from "./IntrinsicElements/Progress";
import { QIntrinsicElements } from "./IntrinsicElements/Q";
import { RpIntrinsicElements } from "./IntrinsicElements/Rp";
import { RtIntrinsicElements } from "./IntrinsicElements/Rt";
import { RubyIntrinsicElements } from "./IntrinsicElements/Ruby";
import { SIntrinsicElements } from "./IntrinsicElements/S";
import { SampIntrinsicElements } from "./IntrinsicElements/Samp";
import { ScriptIntrinsicElements } from "./IntrinsicElements/Script";
import { SearchIntrinsicElements } from "./IntrinsicElements/Search";
import { SectionIntrinsicElements } from "./IntrinsicElements/Section";
import { SelectIntrinsicElements } from "./IntrinsicElements/Select";
import { SelectedcontentIntrinsicElements } from "./IntrinsicElements/Selectedcontent";
import { SlotIntrinsicElements } from "./IntrinsicElements/Slot";
import { SmallIntrinsicElements } from "./IntrinsicElements/Small";
import { SourceIntrinsicElements } from "./IntrinsicElements/Source";
import { SpanIntrinsicElements } from "./IntrinsicElements/Span";
import { StrongIntrinsicElements } from "./IntrinsicElements/Strong";
import { StyleIntrinsicElements } from "./IntrinsicElements/Style";
import { SubIntrinsicElements } from "./IntrinsicElements/Sub";
import { SummaryIntrinsicElements } from "./IntrinsicElements/Summary";
import { SupIntrinsicElements } from "./IntrinsicElements/Sup";
import { SvgIntrinsicElements } from "./IntrinsicElements/Svg";
import { TableIntrinsicElements } from "./IntrinsicElements/Table";
import { TbodyIntrinsicElements } from "./IntrinsicElements/Tbody";
import { TdIntrinsicElements } from "./IntrinsicElements/Td";
import { TemplateIntrinsicElements } from "./IntrinsicElements/Template";
import { TextareaIntrinsicElements } from "./IntrinsicElements/Textarea";
import { TfootIntrinsicElements } from "./IntrinsicElements/Tfoot";
import { ThIntrinsicElements } from "./IntrinsicElements/Th";
import { TheadIntrinsicElements } from "./IntrinsicElements/Thead";
import { TimeIntrinsicElements } from "./IntrinsicElements/Time";
import { TitleIntrinsicElements } from "./IntrinsicElements/Title";
import { TrIntrinsicElements } from "./IntrinsicElements/Tr";
import { TrackIntrinsicElements } from "./IntrinsicElements/Track";
import { UIntrinsicElements } from "./IntrinsicElements/U";
import { UlIntrinsicElements } from "./IntrinsicElements/Ul";
import { VarIntrinsicElements } from "./IntrinsicElements/Var";
import { VideoIntrinsicElements } from "./IntrinsicElements/Video";
import { WbrIntrinsicElements } from "./IntrinsicElements/Wbr";
import { VNode } from "./VNode";

type PrimitiveChild = string | number | boolean | null | undefined;

type dathomirJSX = (
  tag: any,
  props: {
    [key: string]: any;
    children?: dathomirNode;
  } | null,
  key?: string | number,
) => VNode;

type dathomirNode =
  | PrimitiveChild
  | Computed<PrimitiveChild>
  | VNode
  | Computed<VNode>
  | dathomirNode[];

type dathomirElement = VNode;

export namespace JSX {
  export interface IntrinsicElements {
    a: AIntrinsicElements;
    abbr: AbbrIntrinsicElements;
    address: AddressIntrinsicElements;
    area: AreaIntrinsicElements;
    article: ArticleIntrinsicElements;
    aside: AsideIntrinsicElements;
    audio: AudioIntrinsicElements;
    b: BIntrinsicElements;
    base: BaseIntrinsicElements;
    bdi: BdiIntrinsicElements;
    bdo: BdoIntrinsicElements;
    blockquote: BlockquoteIntrinsicElements;
    body: BodyIntrinsicElements;
    br: BrIntrinsicElements;
    button: ButtonIntrinsicElements;
    canvas: CanvasIntrinsicElements;
    caption: CaptionIntrinsicElements;
    cite: CiteIntrinsicElements;
    code: CodeIntrinsicElements;
    col: ColIntrinsicElements;
    colgroup: ColgroupIntrinsicElements;
    data: DataIntrinsicElements;
    datalist: DatalistIntrinsicElements;
    dd: DdIntrinsicElements;
    del: DelIntrinsicElements;
    details: DetailsIntrinsicElements;
    dfn: DfnIntrinsicElements;
    dialog: DialogIntrinsicElements;
    div: DivIntrinsicElements;
    dl: DlIntrinsicElements;
    dt: DtIntrinsicElements;
    em: EmIntrinsicElements;
    embed: EmbedIntrinsicElements;
    fencedframe: FencedframeIntrinsicElements;
    fieldset: FieldsetIntrinsicElements;
    figcaption: FigcaptionIntrinsicElements;
    figure: FigureIntrinsicElements;
    footer: FooterIntrinsicElements;
    form: FormIntrinsicElements;
    h1: H1IntrinsicElements;
    h2: H2IntrinsicElements;
    h3: H3IntrinsicElements;
    h4: H4IntrinsicElements;
    h5: H5IntrinsicElements;
    h6: H6IntrinsicElements;
    head: HeadIntrinsicElements;
    header: HeaderIntrinsicElements;
    hgroup: HgroupIntrinsicElements;
    hr: HrIntrinsicElements;
    html: HtmlIntrinsicElements;
    i: IIntrinsicElements;
    iframe: IframeIntrinsicElements;
    img: ImgIntrinsicElements;
    input: InputIntrinsicElements;
    ins: InsIntrinsicElements;
    kbd: KbdIntrinsicElements;
    label: LabelIntrinsicElements;
    legend: LegendIntrinsicElements;
    li: LiIntrinsicElements;
    link: LinkIntrinsicElements;
    main: MainIntrinsicElements;
    map: MapIntrinsicElements;
    mark: MarkIntrinsicElements;
    math: MathIntrinsicElements;
    menu: MenuIntrinsicElements;
    meta: MetaIntrinsicElements;
    meter: MeterIntrinsicElements;
    nav: NavIntrinsicElements;
    noscript: NoscriptIntrinsicElements;
    object: ObjectIntrinsicElements;
    ol: OlIntrinsicElements;
    optgroup: OptgroupIntrinsicElements;
    option: OptionIntrinsicElements;
    output: OutputIntrinsicElements;
    p: PIntrinsicElements;
    picture: PictureIntrinsicElements;
    pre: PreIntrinsicElements;
    progress: ProgressIntrinsicElements;
    q: QIntrinsicElements;
    rp: RpIntrinsicElements;
    rt: RtIntrinsicElements;
    ruby: RubyIntrinsicElements;
    s: SIntrinsicElements;
    samp: SampIntrinsicElements;
    script: ScriptIntrinsicElements;
    search: SearchIntrinsicElements;
    section: SectionIntrinsicElements;
    select: SelectIntrinsicElements;
    selectedcontent: SelectedcontentIntrinsicElements;
    slot: SlotIntrinsicElements;
    small: SmallIntrinsicElements;
    source: SourceIntrinsicElements;
    span: SpanIntrinsicElements;
    strong: StrongIntrinsicElements;
    style: StyleIntrinsicElements;
    sub: SubIntrinsicElements;
    summary: SummaryIntrinsicElements;
    sup: SupIntrinsicElements;
    svg: SvgIntrinsicElements;
    table: TableIntrinsicElements;
    tbody: TbodyIntrinsicElements;
    td: TdIntrinsicElements;
    template: TemplateIntrinsicElements;
    textarea: TextareaIntrinsicElements;
    tfoot: TfootIntrinsicElements;
    th: ThIntrinsicElements;
    thead: TheadIntrinsicElements;
    time: TimeIntrinsicElements;
    title: TitleIntrinsicElements;
    tr: TrIntrinsicElements;
    track: TrackIntrinsicElements;
    u: UIntrinsicElements;
    ul: UlIntrinsicElements;
    var: VarIntrinsicElements;
    video: VideoIntrinsicElements;
    wbr: WbrIntrinsicElements;
  }

  export type Element = VNode;
  export type ElementType = keyof IntrinsicElements;

  export interface ElementChildrenAttribute {
    children: {};
  }
}

export { dathomirJSX, dathomirNode, dathomirElement };
